AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Application Model (SAM) Deployment
  
Globals:
  Function:
    Timeout: 3

Resources:
  GetAllUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getAllUsersFunction/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        GetAllUsers:
          Type: HttpApi
          Properties:
            Path: /users
            Method: GET
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  GetAllUsersApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
